/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.javaswing.view;

import com.javaswing.model.DienThoai;
import com.javaswing.service.DienThoaiService;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phamn
 */
public class ListDienThoaiFrame extends javax.swing.JFrame {
    DienThoai dienThoai;
    DienThoaiService dienThoaiService;
    DefaultTableModel defaultTableModel;
    
    public ListDienThoaiFrame() {
        initComponents();
        
        setLocation(380, 160);
        
        dienThoai = new DienThoai();
        dienThoaiService = new DienThoaiService();
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        listDienThoaiTable.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("Ma DT");
        defaultTableModel.addColumn("Ten");
        defaultTableModel.addColumn("He Dieu Hanh");
        defaultTableModel.addColumn("RAM");
        defaultTableModel.addColumn("Bo Nho");
        defaultTableModel.addColumn("Gia");
        defaultTableModel.addColumn("So Luong");

        List<DienThoai> list = new ArrayList<>();
        list = dienThoaiService.getAllDienThoai();
        
        for (DienThoai dt : list) {
            defaultTableModel.addRow(new Object[]{dt.getMaDT(), dt.getTenDT(),
                dt.getHeDieuHanh(), dt.getRam(), dt.getBoNho(), dt.getGia(), dt.getSoLuong()});
        }
    }
    
    public void fillTable(){
        defaultTableModel.setRowCount(0);
        
        List<DienThoai> list = new ArrayList<>();
        list = dienThoaiService.getAllDienThoai();
        
        for (DienThoai dt : list) {
            defaultTableModel.addRow(new Object[]{dt.getMaDT(), dt.getTenDT(),
                dt.getHeDieuHanh(), dt.getRam(), dt.getBoNho(), dt.getGia(), dt.getSoLuong()});
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listDienThoaiTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        maDTTextField = new javax.swing.JTextField();
        tenDTTextField = new javax.swing.JTextField();
        boNhoTextField = new javax.swing.JTextField();
        ramTextField = new javax.swing.JTextField();
        heDieuHanhTextField = new javax.swing.JTextField();
        giaTextField = new javax.swing.JTextField();
        soluongTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listDienThoaiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listDienThoaiTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listDienThoaiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listDienThoaiTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listDienThoaiTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("QUAN LY SAN PHAM");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Ma DT :");

        jLabel3.setText("Ten DT:");

        jLabel4.setText("He dieu hanh :");

        jLabel5.setText("RAM :");

        jLabel6.setText("Bo nho :");

        jLabel7.setText("Gia :");

        jLabel8.setText("So luong trong kho:");

        addButton.setText("Them Moi");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Cap Nhap");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Xoa");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(addButton)
                        .addGap(31, 31, 31)
                        .addComponent(updateButton)
                        .addGap(35, 35, 35)
                        .addComponent(deleteButton)
                        .addGap(39, 39, 39)
                        .addComponent(refreshButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boNhoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tenDTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maDTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ramTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heDieuHanhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(giaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soluongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(115, 115, 115)
                        .addComponent(backButton)
                        .addGap(21, 21, 21)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(backButton))
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(heDieuHanhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(maDTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tenDTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(giaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(boNhoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(soluongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ramTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton)
                    .addComponent(refreshButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new MenuManage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        StringBuilder sb = new StringBuilder();
        if(maDTTextField.getText().equals("")){
            sb.append("Ma dien thoai khong duoc de trong! \n");
            maDTTextField.setBackground(Color.red);
        } else {
            maDTTextField.setBackground(Color.white);
        }
        if(tenDTTextField.getText().equals("")){
            sb.append("Ten dien thoai khong duoc de trong! \n");
            tenDTTextField.setBackground(Color.red);
        } else {
            tenDTTextField.setBackground(Color.white);
        }
        if(heDieuHanhTextField.getText().equals("")){
            sb.append("He dieu hanh cua dien thoai khong duoc de trong! \n");
            heDieuHanhTextField.setBackground(Color.red);
        } else {
            heDieuHanhTextField.setBackground(Color.white);
        }
        if(ramTextField.getText().equals("")){
            sb.append("RAM cua dien thoai khong duoc de trong! \n");
            ramTextField.setBackground(Color.red);
        } else {
            ramTextField.setBackground(Color.white);
        }
        if(boNhoTextField.getText().equals("")){
            sb.append("Bo nho cua dien thoai khong duoc de trong! \n");
            boNhoTextField.setBackground(Color.red);
        } else {
            boNhoTextField.setBackground(Color.white);
        }
        if(giaTextField.getText().equals("")){
            sb.append("Gia cua dien thoai khong duoc de trong! \n");
            giaTextField.setBackground(Color.red);
        } else {
            giaTextField.setBackground(Color.white);
        }
        if(soluongTextField.getText().equals("")){
            sb.append("So luong ton kho khong duoc de trong! \n");
            soluongTextField.setBackground(Color.red);
        } else {
            soluongTextField.setBackground(Color.white);
        }
        
        if(sb.length() > 0){
            JOptionPane.showMessageDialog(this, sb.toString(), "Error", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        List<DienThoai> list = dienThoaiService.getAllDienThoai();
        int maDT = Integer.parseInt(maDTTextField.getText());
        
        for (DienThoai dt : list) {
            if(dt.getMaDT() == maDT){
                dienThoai.setMaDT(Integer.parseInt(maDTTextField.getText()));
                dienThoai.setTenDT(tenDTTextField.getText());
                dienThoai.setHeDieuHanh(heDieuHanhTextField.getText());
                dienThoai.setRam(ramTextField.getText());
                dienThoai.setBoNho(heDieuHanhTextField.getText());
                dienThoai.setGia(Float.parseFloat(giaTextField.getText()));
                dienThoai.setSoLuong(Integer.parseInt(soluongTextField.getText()));
                break;
            }
        }
        dienThoaiService.updateDienThoai(dienThoai);
        fillTable();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        StringBuilder sb = new StringBuilder();
        if(maDTTextField.getText().equals("")){
            sb.append("Ma dien thoai khong duoc de trong! \n");
            maDTTextField.setBackground(Color.red);
        } else {
            maDTTextField.setBackground(Color.white);
        }
        if(tenDTTextField.getText().equals("")){
            sb.append("Ten dien thoai khong duoc de trong! \n");
            tenDTTextField.setBackground(Color.red);
        } else {
            tenDTTextField.setBackground(Color.white);
        }
        if(heDieuHanhTextField.getText().equals("")){
            sb.append("He dieu hanh cua dien thoai khong duoc de trong! \n");
            heDieuHanhTextField.setBackground(Color.red);
        } else {
            heDieuHanhTextField.setBackground(Color.white);
        }
        if(ramTextField.getText().equals("")){
            sb.append("RAM cua dien thoai khong duoc de trong! \n");
            ramTextField.setBackground(Color.red);
        } else {
            ramTextField.setBackground(Color.white);
        }
        if(boNhoTextField.getText().equals("")){
            sb.append("Bo nho cua dien thoai khong duoc de trong! \n");
            boNhoTextField.setBackground(Color.red);
        } else {
            boNhoTextField.setBackground(Color.white);
        }
        if(giaTextField.getText().equals("")){
            sb.append("Gia cua dien thoai khong duoc de trong! \n");
            giaTextField.setBackground(Color.red);
        } else {
            giaTextField.setBackground(Color.white);
        }
        if(soluongTextField.getText().equals("")){
            sb.append("So luong ton kho khong duoc de trong! \n");
            soluongTextField.setBackground(Color.red);
        } else {
            soluongTextField.setBackground(Color.white);
        }
        
        if(sb.length() > 0){
            JOptionPane.showMessageDialog(this, sb.toString(), "Error", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        dienThoai.setMaDT(Integer.parseInt(maDTTextField.getText()));
        dienThoai.setTenDT(tenDTTextField.getText());
        dienThoai.setHeDieuHanh(heDieuHanhTextField.getText());
        dienThoai.setRam(ramTextField.getText());
        dienThoai.setBoNho(heDieuHanhTextField.getText());
        dienThoai.setGia(Float.parseFloat(giaTextField.getText()));
        dienThoai.setSoLuong(Integer.parseInt(soluongTextField.getText()));
        
        dienThoaiService.addDienThoai(dienThoai);
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        List<DienThoai> list = dienThoaiService.getAllDienThoai();
        
        int selected = listDienThoaiTable.getSelectedRow();
        
        if(selected >= 0){
            int maDT = (int) listDienThoaiTable.getValueAt(selected, 0);
            
            for (DienThoai dt : list) {
                if(maDT == dt.getMaDT()){
                    dienThoaiService.deleteDienThoai(dienThoai);
                    break;
                }
            }
        }
        
        fillTable();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        maDTTextField.setText("");
        tenDTTextField.setText("");
        heDieuHanhTextField.setText("");
        ramTextField.setText("");
        boNhoTextField.setText("");
        giaTextField.setText("");
        soluongTextField.setText("");
        
        fillTable();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void listDienThoaiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDienThoaiTableMouseClicked
        List<DienThoai> list = dienThoaiService.getAllDienThoai();
        int selectedRow = listDienThoaiTable.getSelectedRow();
        if(selectedRow >= 0){
            int maDT = (int) listDienThoaiTable.getValueAt(selectedRow, 0);
            
            for (DienThoai dt : list) {
                if(maDT == dt.getMaDT()){
                    maDTTextField.setText("" + dt.getMaDT());
                    tenDTTextField.setText(dt.getTenDT());
                    heDieuHanhTextField.setText(dt.getHeDieuHanh());
                    ramTextField.setText(dt.getRam());
                    boNhoTextField.setText(dt.getBoNho());
                    giaTextField.setText("" + dt.getGia());
                    soluongTextField.setText("" + dt.getSoLuong());
                    break;
                }
            }
        }
    }//GEN-LAST:event_listDienThoaiTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListDienThoaiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListDienThoaiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListDienThoaiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListDienThoaiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListDienThoaiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField boNhoTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField giaTextField;
    private javax.swing.JTextField heDieuHanhTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable listDienThoaiTable;
    private javax.swing.JTextField maDTTextField;
    private javax.swing.JTextField ramTextField;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField soluongTextField;
    private javax.swing.JTextField tenDTTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
