/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.javaswing.view;

import com.javaswing.model.ChiNhanh;
import com.javaswing.service.ChiNhanhService;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phamn
 */
public class ListChiNhanhFrame extends javax.swing.JFrame {
    ChiNhanh chiNhanh;
    ChiNhanhService chiNhanhService;
    DefaultTableModel defaultTableModel;
    
    public ListChiNhanhFrame() {
        initComponents();
        
        setLocation(380, 160);
        
        chiNhanh = new ChiNhanh();
        chiNhanhService = new ChiNhanhService();
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        listChiNhanhTable.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("Ma CN");
        defaultTableModel.addColumn("Ten Chi Nhanh");
        defaultTableModel.addColumn("Dia Chi");
        defaultTableModel.addColumn("SDT");
        
        List<ChiNhanh> list = chiNhanhService.getAllChiNhanh();
        
        for (ChiNhanh chiNhanh : list) {
            defaultTableModel.addRow(new Object[]{chiNhanh.getMaCN(), chiNhanh.getTenCN(),
                chiNhanh.getDiaChi(), chiNhanh.getSdt()});
        }
    }
    
    private void fillTable() {
        defaultTableModel.setRowCount(0); // Xoa het du lieu trong bang hien tai
        
        List<ChiNhanh> list = chiNhanhService.getAllChiNhanh();

        for(ChiNhanh cn : list){
            defaultTableModel.addRow(new Object[]{cn.getMaCN(), cn.getTenCN(),
                cn.getDiaChi(), cn.getSdt()});
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listChiNhanhTable = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();
        addChiNhanhButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tenCNTextField = new javax.swing.JTextField();
        diaChiTextField = new javax.swing.JTextField();
        sdtTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cnTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        listChiNhanhTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listChiNhanhTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        listChiNhanhTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listChiNhanhTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listChiNhanhTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listChiNhanhTable);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        addChiNhanhButton.setText("Them Moi");
        addChiNhanhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChiNhanhButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Xoa");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Cap Nhap");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("QUAN LY CHI NHANH");

        jLabel3.setText("DIA CHI :");

        jLabel4.setText("SDT :");

        diaChiTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaChiTextFieldActionPerformed(evt);
            }
        });

        sdtTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdtTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Ma CN :");

        jLabel2.setText("TEN :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 199, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(117, 117, 117)
                        .addComponent(backButton)
                        .addGap(16, 16, 16)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(addChiNhanhButton)
                .addGap(31, 31, 31)
                .addComponent(updateButton)
                .addGap(27, 27, 27)
                .addComponent(deleteButton)
                .addGap(31, 31, 31)
                .addComponent(refreshButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tenCNTextField)
                    .addComponent(cnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diaChiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaChiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tenCNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addChiNhanhButton)
                    .addComponent(deleteButton)
                    .addComponent(refreshButton)
                    .addComponent(updateButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        cnTextField.setText("");
        tenCNTextField.setText("");
        sdtTextField.setText("");
        diaChiTextField.setText("");
        
        fillTable();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void addChiNhanhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChiNhanhButtonActionPerformed
        StringBuilder sb = new StringBuilder();
        if(cnTextField.getText().equals("")){
            sb.append("Ma chi nhanh khong duoc de trong! \n");
            cnTextField.setBackground(Color.red);
        } else {
            cnTextField.setBackground(Color.white);
        }
        if(tenCNTextField.getText().equals("")){
            sb.append("Ten chi nhanh khong duoc de trong! \n");
            tenCNTextField.setBackground(Color.red);
        } else {
            tenCNTextField.setBackground(Color.white);
        }
        if(diaChiTextField.getText().equals("")){
            sb.append("Dia chi cua chi nhanh khong duoc de trong! \n");
            diaChiTextField.setBackground(Color.red);
        } else {
            diaChiTextField.setBackground(Color.white);
        }
        if(sdtTextField.getText().equals("")){
            sb.append("SDT cua chi nhanh khong duoc de trong! \n");
            sdtTextField.setBackground(Color.red);
        } else {
            sdtTextField.setBackground(Color.white);
        }
        
        if(sb.length() > 0){
            JOptionPane.showMessageDialog(this, sb.toString(), "Error", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        chiNhanh.setMaCN(Integer.parseInt(cnTextField.getText()));
        chiNhanh.setTenCN(tenCNTextField.getText());
        chiNhanh.setDiaChi(diaChiTextField.getText());
        chiNhanh.setSdt(Integer.parseInt(sdtTextField.getText()));
        
        chiNhanhService.addChiNhanh(chiNhanh);
        
        fillTable();
    }//GEN-LAST:event_addChiNhanhButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new MenuManage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        List<ChiNhanh> list = chiNhanhService.getAllChiNhanh();
        int selectedRow = listChiNhanhTable.getSelectedRow();
        if(selectedRow >= 0){
            int maCN = (int) listChiNhanhTable.getValueAt(selectedRow, 0);
            for (ChiNhanh chiNhanh : list) {
                if(maCN == chiNhanh.getMaCN() ){
                    chiNhanhService.deleteChiNhanh(chiNhanh);
                    break;
                }
            }
        }
        
        fillTable();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void sdtTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdtTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdtTextFieldActionPerformed

    private void diaChiTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaChiTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaChiTextFieldActionPerformed

    private void listChiNhanhTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listChiNhanhTableMouseClicked
        List<ChiNhanh> list = chiNhanhService.getAllChiNhanh();
        int selectedRow = listChiNhanhTable.getSelectedRow();
        if(selectedRow >= 0){
            int maCN = (int) listChiNhanhTable.getValueAt(selectedRow, 0);
            
            for (ChiNhanh chiNhanh : list) {
                if(maCN == chiNhanh.getMaCN()){
                    cnTextField.setText("" + chiNhanh.getMaCN());
                    tenCNTextField.setText(chiNhanh.getTenCN());
                    sdtTextField.setText("" + chiNhanh.getSdt());
                    diaChiTextField.setText(chiNhanh.getDiaChi());
                    break;
                }
            }
        }
    }//GEN-LAST:event_listChiNhanhTableMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        StringBuilder sb = new StringBuilder();

        if(tenCNTextField.getText().equals("")){
            sb.append("Ten chi nhanh khong duoc de trong! \n");
            tenCNTextField.setBackground(Color.red);
        } else {
            tenCNTextField.setBackground(Color.white);
        }
        if(diaChiTextField.getText().equals("")){
            sb.append("Dia chi cua chi nhanh khong duoc de trong! \n");
            diaChiTextField.setBackground(Color.red);
        } else {
            diaChiTextField.setBackground(Color.white);
        }
        if(sdtTextField.getText().equals("")){
            sb.append("SDT cua chi nhanh khong duoc de trong! \n");
            sdtTextField.setBackground(Color.red);
        } else {
            sdtTextField.setBackground(Color.white);
        }
        
        if(sb.length() > 0){
            JOptionPane.showMessageDialog(this, sb.toString(), "Error", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        List<ChiNhanh> list = chiNhanhService.getAllChiNhanh();
        int tempt = Integer.parseInt(cnTextField.getText());
        
        for (ChiNhanh cn : list) {
            if(cn.getMaCN() == tempt){
                chiNhanh.setMaCN(Integer.parseInt(cnTextField.getText()));
                chiNhanh.setTenCN(tenCNTextField.getText());
                chiNhanh.setDiaChi(diaChiTextField.getText());
                chiNhanh.setSdt(Integer.parseInt(sdtTextField.getText()));
                break;
            }
        }
        chiNhanhService.updateChiNhanh(chiNhanh);
        fillTable();
    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListChiNhanhFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListChiNhanhFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListChiNhanhFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListChiNhanhFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListChiNhanhFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addChiNhanhButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField cnTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField diaChiTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable listChiNhanhTable;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField sdtTextField;
    private javax.swing.JTextField tenCNTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
